version: '3.8'

services:
  site-app:
    container_name: site-app
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - '3001:3000'
    volumes:
      - /app/node_modules
      - ./:/app
    restart: always